#!/usr/bin/env bun
// SPDX-FileCopyrightText: Max Health Inc.
// SPDX-License-Identifier: AGPL-3.0-or-later OR LicenseRef-Commercial
/**
 * Sanitize OpenAPI spec generated by Elysia
 * 
 * Fixes issues where Elysia generates:
 * 1. Incomplete schema references ($ref without #/components/schemas/ prefix)
 * 2. OpenAPI 3.1 constructs in a 3.0.3 spec:
 *    - patternProperties → additionalProperties (3.1-only keyword)
 *    - anyOf with {type: "null"} → nullable: true (3.0.x pattern)
 *    - {type: "null"} standalone → nullable: true
 * 
 * These cause openapi-generator-cli (Java) to NPE when parsing.
 */

import { readFileSync, writeFileSync } from 'fs'
import { resolve } from 'path'

/** Recursive JSON object type for OpenAPI spec manipulation */
type JsonObject = { [key: string]: JsonValue }
type JsonValue = string | number | boolean | null | JsonValue[] | JsonObject

const OPENAPI_PATH = resolve(import.meta.dir, '../dist/openapi.json')

console.log('🔧 Sanitizing OpenAPI spec...')

// Read the OpenAPI spec
const content = readFileSync(OPENAPI_PATH, 'utf-8')
const spec = JSON.parse(content) as JsonObject

let changeCount = 0

// --- Phase 1: Fix OpenAPI 3.1 constructs for 3.0.3 compatibility ---

/**
 * Recursively convert OpenAPI 3.1 constructs to 3.0.3 equivalents:
 * - patternProperties → additionalProperties with the pattern value's schema
 * - anyOf containing {type: "null"} → non-null type with nullable: true
 * - standalone {type: "null"} → {nullable: true}
 */
function downgradeToOpenApi303(obj: JsonObject): void {
  if (!obj || typeof obj !== 'object') return
  if (Array.isArray(obj)) {
    for (const item of obj) if (item && typeof item === 'object' && !Array.isArray(item)) downgradeToOpenApi303(item as JsonObject)
    return
  }

  // Convert patternProperties to additionalProperties
  if ('patternProperties' in obj) {
    const patterns = obj.patternProperties as JsonObject
    const patternKeys = Object.keys(patterns)
    // Use the first pattern's schema as the additionalProperties schema
    if (patternKeys.length > 0) {
      const schema = patterns[patternKeys[0]]
      obj.additionalProperties = schema
    } else {
      obj.additionalProperties = true
    }
    delete obj.patternProperties
    // Ensure type is 'object' if not set
    if (!obj.type) obj.type = 'object'
    changeCount++
  }

  // Convert anyOf with null type to nullable
  if ('anyOf' in obj && Array.isArray(obj.anyOf)) {
    const anyOfArr = obj.anyOf as JsonObject[]
    const nullIndex = anyOfArr.findIndex(
      (s) => s && typeof s === 'object' && s.type === 'null'
    )
    if (nullIndex !== -1) {
      // Remove the null variant
      const nonNull = anyOfArr.filter((_, i) => i !== nullIndex)
      if (nonNull.length === 1) {
        // Single remaining type: flatten and add nullable
        const remaining = nonNull[0]
        delete obj.anyOf
        Object.assign(obj, remaining)
        obj.nullable = true
      } else if (nonNull.length > 1) {
        // Multiple remaining: keep anyOf without null, add nullable
        obj.anyOf = nonNull
        obj.nullable = true
      } else {
        // Only null type — make it nullable with no specific type
        delete obj.anyOf
        obj.nullable = true
      }
      changeCount++
    }
  }

  // Convert standalone {type: "null"} to {nullable: true}
  if (obj.type === 'null') {
    delete obj.type
    obj.nullable = true
    changeCount++
  }

  // Recurse into all nested objects
  for (const key of Object.keys(obj)) {
    const val = obj[key]
    if (val && typeof val === 'object' && !Array.isArray(val)) {
      downgradeToOpenApi303(val as JsonObject)
    } else if (Array.isArray(val)) {
      for (const item of val) if (item && typeof item === 'object' && !Array.isArray(item)) downgradeToOpenApi303(item as JsonObject)
    }
  }
}

console.log('  Downgrading OpenAPI 3.1 constructs to 3.0.3 compatibility...')
downgradeToOpenApi303(spec)

// Set the version field to match the now-valid 3.0.3 constructs
if (typeof spec.openapi === 'string' && spec.openapi.startsWith('3.1.')) {
  spec.openapi = '3.0.3'
  changeCount++
  console.log('  ✓ Downgraded openapi version field to 3.0.3')
}

// --- Phase 2: Fix incomplete $ref references ---

// Function to recursively fix $ref in an object
function fixRefs(obj: JsonObject): void {
  if (!obj || typeof obj !== 'object') return

  for (const key in obj) {
    if (key === '$ref' && typeof obj[key] === 'string') {
      const ref = obj[key]
      
      // Fix incomplete references that don't start with #
      if (!ref.startsWith('#') && !ref.startsWith('http')) {
        // Check if this schema exists in components
        const schemaName = ref
        const components = spec.components as JsonObject | undefined
        const schemas = components?.schemas as JsonObject | undefined
        const schemaExists = schemas?.[schemaName]
        
        if (schemaExists) {
          // Fix the reference to use proper JSON Pointer
          obj[key] = `#/components/schemas/${ref}`
          changeCount++
          console.log(`  ✓ Fixed incomplete reference: "${ref}" -> "#/components/schemas/${ref}"`)
        } else {
          // For redirect responses (like /authorize, /login, /logout), remove the response
          // since redirects don't have a JSON body
          console.log(`  ⚠ Warning: Schema "${ref}" doesn't exist, will remove response schema`)
          // Return a marker so parent can remove this
          obj._removeMe = true
          changeCount++
        }
      }
    } else if (obj[key] && typeof obj[key] === 'object') {
      fixRefs(obj[key] as JsonObject)
      
      // Clean up marked objects
      const nested = obj[key] as JsonObject | null
      if (nested?._removeMe) {
        // For redirect endpoints, remove the entire content/application/json section
        if (key === 'schema') {
          delete obj[key]
        }
      }
    }
  }
}

// Fix all references in the spec
fixRefs(spec)

// Clean up responses with empty content for redirect endpoints
function cleanupEmptyResponses(obj: JsonObject): void {
  if (!obj || typeof obj !== 'object') return

  for (const key in obj) {
    if (key === 'responses' && obj[key] && typeof obj[key] === 'object') {
      const responses = obj[key] as JsonObject
      for (const statusCode in responses) {
        const response = responses[statusCode] as JsonObject
        if (response?.content && typeof response.content === 'object') {
          const content = response.content as JsonObject
          const jsonContent = content['application/json'] as JsonObject | undefined
          if (jsonContent && !jsonContent.schema) {
            // Remove empty content
            delete response.content
            response.description = response.description || 'Redirect response'
            console.log(`  ✓ Removed empty content from response ${statusCode}`)
            changeCount++
          }
        }
      }
    }
    
    if (obj[key] && typeof obj[key] === 'object' && !Array.isArray(obj[key])) {
      cleanupEmptyResponses(obj[key] as JsonObject)
    }
  }
}

cleanupEmptyResponses(spec)

// --- Phase 3: Fix empty requestBody content (Elysia OpenAPI bug with custom `parse` functions) ---
// When a route uses a custom `parse` function, Elysia's OpenAPI generator emits
// `requestBody: { content: {}, required: true }` even though `body` schema is defined.
// See: https://github.com/elysiajs/elysia/issues/1825
// We inject the proper schema from our TypeBox definitions for affected routes.
const emptyRequestBodyFixes: Record<string, { title: string; schema: JsonObject }> = {
  '/auth/token': {
    title: 'TokenRequest',
    schema: {
      title: 'TokenRequest',
      type: 'object',
      required: ['grant_type'],
      properties: {
        grant_type: { type: 'string', description: 'OAuth2 grant type (authorization_code, refresh_token, client_credentials, password, urn:ietf:params:oauth:grant-type:token-exchange)' },
        code: { type: 'string', description: 'Authorization code (for authorization_code grant)', nullable: true },
        redirect_uri: { type: 'string', description: 'Redirect URI used in authorization request', nullable: true },
        client_id: { type: 'string', description: 'OAuth2 client ID', nullable: true },
        client_secret: { type: 'string', description: 'OAuth2 client secret', nullable: true },
        code_verifier: { type: 'string', description: 'PKCE code verifier', nullable: true },
        refresh_token: { type: 'string', description: 'Refresh token (for refresh_token grant)', nullable: true },
        scope: { type: 'string', description: 'Requested scopes (space-separated)', nullable: true },
        audience: { type: 'string', description: 'Target audience for the token', nullable: true },
        resource: { type: 'string', description: 'Target resource URI (RFC 8707 Resource Indicators)', nullable: true },
        username: { type: 'string', description: 'Username (for password grant)', nullable: true },
        password: { type: 'string', description: 'Password (for password grant)', nullable: true },
        client_assertion_type: { type: 'string', description: 'Client assertion type for JWT authentication', nullable: true },
        client_assertion: { type: 'string', description: 'Client assertion JWT for authentication', nullable: true },
        subject_token: { type: 'string', description: 'Security token to be exchanged (for token-exchange grant)', nullable: true },
        subject_token_type: { type: 'string', description: 'Type of subject_token (urn:ietf:params:oauth:token-type:access_token)', nullable: true },
        requested_token_type: { type: 'string', description: 'Type of requested token (urn:ietf:params:oauth:token-type:access_token)', nullable: true },
      }
    }
  }
}

if (spec.paths) {
  for (const [path, fix] of Object.entries(emptyRequestBodyFixes)) {
    const paths = spec.paths as JsonObject
    const pathObj = paths[path] as JsonObject | undefined
    const operation = pathObj?.post as JsonObject | undefined
    const requestBody = operation?.requestBody as JsonObject | undefined
    const content = requestBody?.content as JsonObject | undefined
    if (requestBody && content && Object.keys(content).length === 0) {
      requestBody.content = {
        'application/x-www-form-urlencoded': { schema: fix.schema },
        'application/json': { schema: fix.schema },
      }
      console.log(`  ✓ Injected missing requestBody schema for POST ${path} (${fix.title})`)
      changeCount++
    }
  }
}

// Remove WebSocket endpoints (not part of OpenAPI 3.0.x)
if (spec.paths && typeof spec.paths === 'object') {
  for (const pathItem of Object.values(spec.paths as JsonObject)) {
    if (pathItem && typeof pathItem === 'object' && !Array.isArray(pathItem) && 'ws' in pathItem) {
      delete (pathItem as JsonObject).ws
      console.log(`  ✓ Removed WebSocket endpoint`)
      changeCount++
    }
  }
}

// Write the sanitized spec back
const sanitizedJson = JSON.stringify(spec, null, 2)
writeFileSync(OPENAPI_PATH, sanitizedJson)

// Also update the mcp-server copy (which was written before sanitization)
const mcpServerPath = resolve(import.meta.dir, '../../mcp-server/openapi.json')
try {
  writeFileSync(mcpServerPath, sanitizedJson)
  console.log(`  ✓ Updated mcp-server/openapi.json with sanitized spec`)
} catch {
  // mcp-server directory may not exist in all environments
}

if (changeCount > 0) {
  console.log(`✅ Sanitized OpenAPI spec: ${changeCount} changes made`)
} else {
  console.log('✅ OpenAPI spec is already valid, no changes needed')
}
